### ISSUE TITLE
2014

### ISSUE THREAD

**Issue by letarg0** [aviarypl/aviarypl.github.io#3]
strona nie aktualizowana od ....

swoja droga to uzywacie pontoona?
da sie tego uzywac we wlasnych projektach? czy jest szansa dodania jakiegos projektu? np. debian www

**Comment by splewako** [comment]
> strona nie aktualizowana od ....

Czy coś konkretnie powinniśmy zmienić?

> swoja droga to uzywacie pontoona?
> da sie tego uzywac we wlasnych projektach? czy jest szansa dodania jakiegos projektu? np. debian www

Szczątkowo, średnio i raczej nie (ale to [open source](https://github.com/mozilla/pontoon)).

**Comment by splewako** [comment]
> Czy coś konkretnie powinniśmy zmienić?

Zakładam, że nie. Jeśli jednak to proszę o dokładny opis w nowym zgłoszeniu, to zamykam.
